# Day 63 — Matrices + NumPy Dot Products
### Math Gap Day 1 of 3 | Bridge to ML Foundations

---

**Why this day exists:**  
Every ML algorithm you'll use in Months 7–10 — linear regression, neural nets, PCA, transformers — runs on matrix math underneath. NumPy is the engine. This day gives you the intuition + hands-on skill to never be surprised by a shape error or a dot product again.

**Today's scope (only skills you've already covered):**  
Python lists → NumPy arrays → matrix operations → dot products → broadcasting → real DS application

---

## 📋 SECTION 1 — Raw Data (Do Not Modify)

| Use this data across all exercises. Never overwrite these variables. |

In [22]:
# ============================================================
# RAW DATA — DO NOT MODIFY BELOW THIS LINE
# ============================================================
import numpy as np

# --- Dataset A: Sales matrix (3 products x 4 regions) ---
# Rows = Products (Laptop, Phone, Tablet)
# Columns = Regions (North, South, East, West)
sales_raw = np.array([
    [120, 95,  140, 80],   # Laptop
    [200, 175, 210, 190],  # Phone
    [ 85,  70,  90, 65]    # Tablet
])

# --- Dataset B: Price vector (1 price per product) ---
prices_raw = np.array([45000, 18000, 25000])   # INR

# --- Dataset C: Cost matrix (3 products x 2 cost types) ---
# Cost types = Manufacturing, Shipping
costs_raw = np.array([
    [28000, 1200],   # Laptop
    [10000,  500],   # Phone
    [14000,  800]    # Tablet
])

# --- Dataset D: Region weights (importance scores, sum=1) ---
region_weights_raw = np.array([0.30, 0.25, 0.35, 0.10])

# --- Dataset E: 2x2 transformation matrix (for geometry concept) ---
transform_raw = np.array([[2, 1], [0, 3]])

# ============================================================
print("Raw data loaded. Shapes:")
print(f"  sales_raw:          {sales_raw.shape}")
print(f"  prices_raw:         {prices_raw.shape}")
print(f"  costs_raw:          {costs_raw.shape}")
print(f"  region_weights_raw: {region_weights_raw.shape}")
print(f"  transform_raw:      {transform_raw.shape}")

Raw data loaded. Shapes:
  sales_raw:          (3, 4)
  prices_raw:         (3,)
  costs_raw:          (3, 2)
  region_weights_raw: (4,)
  transform_raw:      (2, 2)


---
## 📚 SECTION 2 — Concept Notes

Read this before attempting the practice tasks. Don't skip it — these mental models prevent shape errors in real ML code.

---

### 2.1 What is a Matrix?

A **matrix** is a 2D grid of numbers — rows and columns.  
In NumPy: a 2D array with shape `(rows, cols)`.

```
sales_raw shape = (3, 4)
               ↑    ↑
          3 products  4 regions
```

**Mental model:** Think of every matrix as a table. The shape tells you `(#rows, #columns)`.

---

### 2.2 Why Matrices in DS/ML?

| You'll see this in... | Matrix represents... |
|---|---|
| Linear Regression | Feature matrix X → shape (n_samples, n_features) |
| Neural Networks | Weights W → shape (input_size, output_size) |
| PCA | Covariance matrix → shape (n_features, n_features) |
| Pandas DataFrame | `.values` → NumPy matrix internally |
| TF-IDF (NLP) | Document-term matrix → shape (n_docs, n_terms) |

---

### 2.3 The Dot Product — Core Operation

**Vector dot product** (1D × 1D → scalar):  
```
a = [1, 2, 3]  
b = [4, 5, 6]  
dot(a, b) = 1×4 + 2×5 + 3×6 = 32
```
Rule: **element-wise multiply, then sum**.

**Matrix multiplication** (2D × 1D → 1D):  
```
A shape (3,4) × b shape (4,) → result shape (3,)
Inner dimensions must match: 4 == 4 ✓
```

**The shape rule (memorise this):**  
```
(m, n) @ (n, p) → (m, p)
         ↑↑
   these must match
```

---

### 2.4 Broadcasting — NumPy's Superpower

Broadcasting lets NumPy operate on arrays of different shapes **without copying data**.

```python
# Without broadcasting (naive)
for i in range(3):
    result[i] = sales[i] * 1.18   # apply GST to each row

# With broadcasting (NumPy way)
result = sales * 1.18             # NumPy stretches 1.18 across all elements
```

**Broadcasting rules:**  
1. Shapes are compared right-to-left  
2. Dimensions must be equal OR one of them must be 1  
3. Missing dimensions are treated as 1  

```
sales_raw   shape: (3, 4)
scalar 1.18 shape: ()     → broadcast to (3, 4) ✓

sales_raw   shape: (3, 4)
prices_raw  shape: (3,)   → reshape to (3,1) first, then broadcast to (3,4) ✓
```

---

### 2.5 Common Mistakes → Fixes

| Mistake | Error | Fix |
|---|---|---|
| `(3,4) @ (3,)` | shapes not aligned | Transpose: `(3,4) @ (4,)` |
| `prices * sales` when shapes differ | operands broadcast error | `prices.reshape(3,1) * sales` |
| Treating `np.dot` and `*` the same | wrong results silently | `*` is element-wise; `@` or `np.dot` is matrix multiply |
| Forgetting `.T` for transpose | shape error | `A.T` swaps rows↔cols: `(3,4).T → (4,3)` |


---
## ✏️ SECTION 3 — Practice Tasks

**Rules:**  
1. Write a plain-English comment explaining what you're about to do **before** writing any code  
2. Use only `sales_raw`, `prices_raw`, `costs_raw`, `region_weights_raw`, `transform_raw`  
3. Never modify raw variables — always work on a copy or use the result directly

---

### PART A — Matrix Inspection (20 pts)

**A1 (4 pts):** Print the shape, number of dimensions (ndim), and total elements (size) of `sales_raw`. Add a plain-English label before each printed value.

In [23]:
# A1: Inspect the shape, dimensions, and total elements of sales_raw
# YOUR CODE HERE
print("=== A1 ===")
print(f"Shape:       {sales_raw.shape}")
print(f"Dimensions:  {sales_raw.ndim}")
print(f"Total cells: {sales_raw.size}")

=== A1 ===
Shape:       (3, 4)
Dimensions:  2
Total cells: 12


**A2 (4 pts):** Extract only the **Phone row** (row index 1) and only the **East column** (column index 2) as separate variables. Print both with labels.

In [24]:
# A2: Slice Phone row and East column from sales_raw
# YOUR CODE HERE
print("\n=== A2 ===")
phone_row = sales_raw[1]
east_col = sales_raw[:, 2]
print(f"Phone row:   {phone_row}")
print(f"East column: {east_col}")



=== A2 ===
Phone row:   [200 175 210 190]
East column: [140 210  90]


**A3 (4 pts):** Transpose `sales_raw` so rows become regions and columns become products. Store it as `sales_T`. Print the shape before and after.

In [25]:
# A3: Transpose sales_raw — regions as rows, products as columns
# YOUR CODE HERE
print("\n=== A3 ===")
sales_T = sales_raw.T
print(f"Before transpose: {sales_raw.shape}")
print(f"After transpose:  {sales_T.shape}")


=== A3 ===
Before transpose: (3, 4)
After transpose:  (4, 3)


**A4 (4 pts):** Create a new matrix `sales_with_gst` by applying 18% GST to every unit in `sales_raw` using broadcasting (no loops). Print the first row of both original and GST version.

In [26]:
# A4: Apply 18% GST to all sales values using broadcasting
# YOUR CODE HERE
print("\n=== A4 ===")
sales_with_gst = sales_raw * 1.18
print(f"Original first row: {sales_raw[0]}")
print(f"GST first row:      {sales_with_gst[0]}")


=== A4 ===
Original first row: [120  95 140  80]
GST first row:      [141.6 112.1 165.2  94.4]


**A5 (4 pts):** Find the **maximum sales** in each region (column-wise max) and the **total sales** per product (row-wise sum). Print both with labels.

In [27]:
# A5: Column-wise max per region; row-wise sum per product
# YOUR CODE HERE
print("\n=== A5 ===")
print(f"Max per region (col):  {sales_raw.max(axis=0)}")
print(f"Total per product (row): {sales_raw.sum(axis=1)}")


=== A5 ===
Max per region (col):  [200 175 210 190]
Total per product (row): [435 775 310]


---
### PART B — Dot Products (25 pts)

**B1 (5 pts):** Calculate **total revenue per product** by doing a dot product between `sales_raw` (3×4) and `region_weights_raw` (4,). This gives weighted average sales per product. Multiply by `prices_raw` to get weighted revenue. Print the result as `[Product: Revenue]`.

In [28]:
# B1: Dot product of sales_raw and region_weights_raw → weighted sales per product
#     Then multiply by prices to get weighted revenue per product
# YOUR CODE HERE
products = ['Laptop','Phone','Tablet']
regions = ['North','South','East','West']
print("\n=== B1 ===")
weighted_sales = sales_raw @ region_weights_raw  # (3,4) @ (4,) = (3,)
weighted_revenue = weighted_sales * prices_raw
for p, r in zip(products, weighted_revenue):
    print(f"  {p}: ₹{r:,.0f}")



=== B1 ===
  Laptop: ₹5,253,750
  Phone: ₹3,532,500
  Tablet: ₹2,025,000


**B2 (5 pts):** Calculate **total revenue per region** (not per product).  
Hint: You need `prices_raw` (shape 3,) and `sales_raw` (shape 3×4). Think about which dimension to dot along. Result shape should be `(4,)` — one revenue figure per region.

In [29]:
# B2: Revenue per region — dot prices with sales columns
#     Think: prices shape (3,) dot sales_T shape (3,4)... what's the right arrangement?
# YOUR CODE HERE
products = ['Laptop','Phone','Tablet']
regions = ['North','South','East','West']
print("\n=== B2 ===")
revenue_per_region = prices_raw @ sales_raw  # (3,) @ (3,4) = (4,)
for reg, rev in zip(regions, revenue_per_region):
    print(f"  {reg}: ₹{rev:,}")



=== B2 ===
  North: ₹11,125,000
  South: ₹9,175,000
  East: ₹12,330,000
  West: ₹8,645,000


**B3 (5 pts):** Calculate **profit per product** using `costs_raw` (3×2).  
- Total cost per product = sum of manufacturing + shipping costs (row-wise sum of costs_raw)  
- Total revenue per product = sum of all 4 regions (row-wise sum of sales_raw multiplied by prices_raw — use broadcasting)  
- Profit = Revenue − Cost. Print as `[Product: Profit]`.

In [30]:
# B3: Profit per product = (sales units * price) - (mfg cost + shipping cost)
# YOUR CODE HERE
products = ['Laptop','Phone','Tablet']
regions = ['North','South','East','West']
print("\n=== B3 ===")
total_cost = costs_raw.sum(axis=1)  # (3,)
units_sold = sales_raw.sum(axis=1)  # (3,)
total_revenue_product = units_sold * prices_raw
profit = total_revenue_product - total_cost
for p, prof in zip(products, profit):
    print(f"  {p}: ₹{prof:,}")



=== B3 ===
  Laptop: ₹19,545,800
  Phone: ₹13,939,500
  Tablet: ₹7,735,200


**B4 (5 pts):** Apply `transform_raw` (2×2 matrix) to the vector `[3, 2]` using `np.dot`. Then manually verify by computing the result by hand (as a comment). Explain in a markdown cell below: what does matrix multiplication actually do to a vector geometrically?

In [31]:
# B4: Matrix-vector multiplication — apply transform_raw to vector [3, 2]
# Manual check as comment: row0 dot [3,2] = ?, row1 dot [3,2] = ?
# YOUR CODE HERE
print("\n=== B4 ===")
v = np.array([3, 2])
result = np.dot(transform_raw, v)
print(f"  transform @ [3,2] = {result}")
# Manual: row0=[2,1] · [3,2] = 2*3+1*2=8; row1=[0,3] · [3,2] = 0*3+3*2=6



=== B4 ===
  transform @ [3,2] = [8 6]


*B4 explanation — what does matrix multiplication do to a vector geometrically?*

> Multiplying a vector by a matrix applies a **linear transformation**—it stretches, shears, rotates, or reflects the vector into a new coordinate system.  
> In this example, `transform_raw = [[2,1],[0,3]]` scales the x‑component by 2 and pushes it upward (shear), while scaling the y‑component by 3, moving the original point `[3,2]` to `[8,6]`.

**B5 (5 pts):** Create a **2×2 matrix multiplication** from scratch (without using any raw data):  
- A = `[[1,2],[3,4]]`  
- B = `[[5,0],[1,3]]`  
- Compute `A @ B` using NumPy  
- Then verify element [0,0] and [1,1] manually (as comments)  
- Print result with shape

In [32]:
# B5: Manual 2x2 matrix multiplication and NumPy verification
# Manual: A@B [0,0] = row0 of A · col0 of B = 1*5 + 2*1 = ?
#         A@B [1,1] = row1 of A · col1 of B = 3*0 + 4*3 = ?
# YOUR CODE HERE
print("\n=== B5 ===")
A = np.array([[1,2],[3,4]])
B = np.array([[5,0],[1,3]])
AB = A @ B
print(f"  A @ B =\n{AB}")
print(f"  Shape: {AB.shape}")
# Manual: [0,0]=1*5+2*1=7; [1,1]=3*0+4*3=12



=== B5 ===
  A @ B =
[[ 7  6]
 [19 12]]
  Shape: (2, 2)


---
### PART C — Broadcasting Deep Dive (20 pts)

**C1 (5 pts):** Calculate **revenue per unit sold** for each product-region combination.  
`sales_raw` shape = (3,4). `prices_raw` shape = (3,).  
You need to multiply each row of sales_raw by the corresponding product price.  
Try `sales_raw * prices_raw` first — it will fail. Fix it with `.reshape()`. Print result shape and first row.

In [33]:
# C1: Revenue matrix — multiply each product row by its price
#     prices_raw is (3,) but we need (3,1) to broadcast across 4 regions
# YOUR CODE HERE
print("\n=== C1 ===")
revenue_matrix = sales_raw * prices_raw.reshape(3, 1)  # (3,4) * (3,1) → (3,4)
print(f"  Revenue matrix shape: {revenue_matrix.shape}")
print(f"  First row (Laptop): {revenue_matrix[0]}")



=== C1 ===
  Revenue matrix shape: (3, 4)
  First row (Laptop): [5400000 4275000 6300000 3600000]


**C2 (5 pts):** Normalise `sales_raw` so each value is expressed as a **percentage of its product's total sales** (row-wise normalisation). Every row should sum to 1.0 after normalisation. Print normalised matrix rounded to 2 decimals and verify one row sums to 1.

In [34]:
# C2: Row-wise normalisation — each cell = cell / row_sum
#     Use keepdims=True so broadcasting works without reshape
# YOUR CODE HERE
print("\n=== C2 ===")
row_sums = sales_raw.sum(axis=1, keepdims=True)  # (3,1)
sales_norm = sales_raw / row_sums
print(np.round(sales_norm, 2))
print(f"  Row 0 sum check: {sales_norm[0].sum():.1f}")



=== C2 ===
[[0.28 0.22 0.32 0.18]
 [0.26 0.23 0.27 0.25]
 [0.27 0.23 0.29 0.21]]
  Row 0 sum check: 1.0


**C3 (5 pts):** Find which **product-region combination** has the **highest revenue** (units × price).  
Use `np.argmax()` with `np.unravel_index()` to find the exact row and column index. Print:  
`"Highest revenue: {Product} in {Region} — ₹{Revenue:,}"`

In [35]:
# C3: Find the highest revenue cell across the entire revenue matrix
# Use revenue matrix from C1, find flat argmax, convert to (row,col) with unravel_index
products = ['Laptop', 'Phone', 'Tablet']
regions = ['North', 'South', 'East', 'West']
# YOUR CODE HERE
print("\n=== C3 ===")
flat_idx = np.argmax(revenue_matrix)
row, col = np.unravel_index(flat_idx, revenue_matrix.shape)
print(f"  Highest revenue: {products[row]} in {regions[col]} — ₹{revenue_matrix[row,col]:,}")



=== C3 ===
  Highest revenue: Laptop in East — ₹6,300,000


**C4 (5 pts):** Write a **written business insight** (Number + Reason + Action format) based on what B1, B2, and C3 together reveal about the product-region performance. This goes in the cell below — no code, just your written analysis.

**C4 — Business Insight (Number + Reason + Action):**

> **Number:** The Laptop‑East product‑region combination generates the highest cell revenue of **₹6,300,000** (from C3), and the East region alone contributes the largest total revenue of **₹12,330,000** (from B2). However, the weighted importance of East is only 35% (region_weights_raw), meaning its actual outperformance is even stronger than its assigned weight suggests.  
> **Reason:** Laptops command the highest unit price (₹45,000) and achieve their maximum unit sales in the East (140 units). This price‑volume combination makes the East region the dominant revenue driver, primarily fuelled by laptop sales, while Phones and Tablets under‑index in the East despite its high revenue potential.  
> **Action:** Allocate additional marketing budget and inventory stock for Laptops specifically to the East region to further capitalise on this high‑performing segment. Simultaneously, investigate why Phone and Tablet penetration in the East lags—perhaps through targeted promotions—to lift overall regional portfolio balance and reduce dependency on a single product.

---
### PART D — ML Connection (15 pts)

**D1 (8 pts):** Simulate **one forward pass of a neural network layer**.  
A single linear layer computes: `output = X @ W + b`  
- `X` = input features, shape (5, 3) — 5 data points, 3 features each (create with `np.random.seed(42); X = np.random.randn(5,3)`)  
- `W` = weight matrix, shape (3, 2) — maps 3 inputs to 2 neurons (use `np.random.seed(7); W = np.random.randn(3,2)`)  
- `b` = bias vector, shape (2,) — `b = np.array([0.5, -0.5])`  
- Compute `output`, print its shape, and explain in a comment why the output shape makes sense.

In [36]:
# D1: Simulate one linear layer forward pass: output = X @ W + b
# X shape (5,3) — 5 samples, 3 features
# W shape (3,2) — 3 inputs mapped to 2 neurons
# b shape (2,)  — 1 bias per output neuron, broadcast across 5 samples
# YOUR CODE HERE
print("\n=== D1 ===")
np.random.seed(42); X = np.random.randn(5, 3)
np.random.seed(7);  W = np.random.randn(3, 2)
b = np.array([0.5, -0.5])
output = X @ W + b  # (5,3)@(3,2)+(2,) → (5,2)
print(f"  Output shape: {output.shape}")
print(f"  Output (5 samples × 2 neurons):\n{np.round(output, 3)}")



=== D1 ===
  Output shape: (5, 2)
  Output (5 samples × 2 neurons):
[[ 0.824 -0.786]
 [ 3.252 -1.306]
 [ 3.565 -0.924]
 [ 1.769 -0.943]
 [ 2.207 -1.396]]


**D2 ★ Bonus (10 pts):** Simulate **linear regression prediction** on the sales data.  
- Features `X` = first 3 columns of `sales_raw` (shape 3×3) as float  
- Target `y` = last column of `sales_raw` (West region) as float  
- Compute the **least-squares weights**: `w = (X^T X)^{-1} X^T y` using `np.linalg.inv` and `np.dot`  
- Predict `y_hat = X @ w`  
- Print actual vs predicted for all 3 products  
- Explain in a markdown cell: what does this formula actually compute?

In [37]:
# D2★ BONUS: Least-squares linear regression using matrix math
# Formula: w = (X^T @ X)^{-1} @ X^T @ y
# This is the closed-form solution to minimising sum of squared errors
# YOUR CODE HERE
print("\n=== D2 BONUS ===")
X_lr = sales_raw[:, :3].astype(float)
y_lr = sales_raw[:, 3].astype(float)
w_lr = np.linalg.inv(X_lr.T @ X_lr) @ X_lr.T @ y_lr
y_hat = X_lr @ w_lr
for p, act, pred in zip(products, y_lr, y_hat):
    print(f"  {p}: actual={act:.0f}, predicted={pred:.1f}")


=== D2 BONUS ===
  Laptop: actual=80, predicted=80.0
  Phone: actual=190, predicted=190.0
  Tablet: actual=65, predicted=65.0


*D2 explanation — what does `w = (X^T X)^{-1} X^T y` actually compute?*

> This formula computes the **least‑squares weights** that minimise the sum of squared residuals (errors) between the actual target `y` and the predicted values `X @ w`.  
> Geometrically, it finds the orthogonal projection of `y` onto the column space of the feature matrix `X`. Because the sales data matrix is full‑rank (3×3 with three independent columns), the solution perfectly interpolates the three data points, resulting in zero error on the training data.

---
## 🏆 SECTION 4 — Scoring Rubric

| Part | Task | Points | What's Checked |
|------|------|--------|----------------|
| A | A1 — shape/ndim/size | 4 | All 3 attributes printed with labels |
| A | A2 — row/col slicing | 4 | Correct Phone row + East col using proper indexing |
| A | A3 — transpose | 4 | `.T` used, shapes printed before and after |
| A | A4 — GST broadcasting | 4 | `* 1.18`, no loop, first rows printed |
| A | A5 — axis aggregation | 4 | `max(axis=0)` and `sum(axis=1)` both correct |
| **A Total** | | **20** | |
| B | B1 — dot product revenue | 5 | `(3,4) @ (4,)` correct, products labelled |
| B | B2 — revenue per region | 5 | `prices @ sales` giving shape `(4,)` |
| B | B3 — profit per product | 5 | Correct cost + revenue calc, broadcasting used |
| B | B4 — transform + explanation | 5 | NumPy result correct + written geometric explanation |
| B | B5 — 2×2 matmul | 5 | `@` operator used, manual verify as comment |
| **B Total** | | **25** | |
| C | C1 — reshape broadcasting | 5 | `.reshape(3,1)` used, shape printed |
| C | C2 — row normalisation | 5 | `keepdims=True`, sum check = 1.0 |
| C | C3 — argmax + unravel | 5 | `np.unravel_index` used, NRA formatted output |
| C | C4 — business insight | 5 | Number + Reason + Action, references actual output |
| **C Total** | | **20** | |
| D | D1 — forward pass | 8 | Correct shapes, comment explaining output shape |
| D | D2★ — OLS regression | 10 | Correct formula, actual vs predicted printed, explanation |
| **D Total** | | **8 + 10★** | |
| **GRAND TOTAL** | | **73 pts (+10 bonus)** | |

---

## 🎤 Interview Framing

*"In your ML work, how do you think about matrix operations?"*

**Your answer should be:**  
"I think about every ML model as a sequence of matrix transformations. In linear regression the prediction is just a dot product — weights times features. In a neural net layer it's the same thing plus a bias and an activation. Once I understood that `output = X @ W + b` is the whole forward pass, matrix shapes stopped being confusing — I just trace `(n_samples, n_features) @ (n_features, n_outputs)` and the result shape tells me what I'm producing."

---

## 📁 GitHub Note

This notebook is **Month 3 Math Bridge Day 1/3**. Push to `Month3-Python-Portfolio` after completing all 3 math days (63–65) as a single commit: `"Add math bridge: matrices, gradients, CLT"`. This shows any MSc/employer that you understand the foundations, not just the library calls.